# Application
server:
    port: 8080
    servlet:
        context-path: /api

spring:
    application:
        name: productos-service

    datasource:
        url: jdbc:postgresql://localhost:5432/productos_db
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                '[format_sql]': true

# API Key
app:
    api.key: linktic-2025

# Swagger
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html