# Application
server:
    port: 8081
    servlet:
        context-path: /api

spring:
    application:
        name: inventario-service


# Database
    datasource:
        url: jdbc:postgresql://localhost:5433/inventario_db
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver

# JPA
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
            '[format_sql]': true

# API Key
app:
    api.key: linktic-2025

# Productos Service
productos:
    service.url: http://localhost:8080
    service.api-key: linktic-2025

# Swagger
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html